version: "3.4"

services:
    sql-server-db:
        container_name: sql-server-db 
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
           - "1433:1433"
        environment:
          SA_PASSWORD: "zaq1@WSX"
          ACCEPT_EULA: "Y"
    pizzarestaurantapi:
        image: ${DOCKER_REGISTRY-}pizzarestaurantapi
        build:
            context: .
            dockerfile: PizzaRestaurantAPI/Dockerfile
    